---
- name: Standardizing Logging Host
  hosts: all
  gather_facts: yes
  vars:
     logging_host_default: "logging host 1.1.1.1"
  tasks:
    - name: Determine IP according to inventory file name
      set_fact:
        specify_log_host: >-
          {% if inventory_name == "Kenny_Test2" %}
          logging host 2.2.2.2
          {% elif inventory_name == "Kenny_Test3" %}
          logging host 3.3.3.3
          {% elif inventory_name == "Kenny_Test4" %}
          logging host 4.4.4.4
          {% endif %}

    - name: Gather device information
      cisco.ios.ios_facts:
      register: device_facts

    - name: Get show run
      cisco.ios.ios_command:
        commands:
          - "show run | include logging host"
      register: logging_output_v1

    - name: Get show ip vrf
      cisco.ios.ios_command:
        commands:
          - "show ip vrf"
      register: ip_vrf_output_v1

    - name: Check if logging host is empty or not
      set_fact:
        is_empty: >
          {{
            logging_output_v1.stdout_lines |
            flatten |
            select('match', '^.+$') |
            length == 0
          }}

    - name: Check if vrf supported
      set_fact:
        vrf_sup: "{{ 'Mgmt-vrf' in ip_vrf_output_v1.stdout[0] }}"

    - name: If logging host is not empty, run tasks
      block:
        - name: Create remove command
          set_fact:
            remove_command: >
              {{
                logging_output_v1.stdout_lines |
                flatten |
                map('regex_replace', '^', 'no ') |
                list
              }}

        - name: test
          debug:
            var: remove_command

#        - name: Remove logging hosts
#          cisco.ios.ios_config:
#            lines: "{{ remove_command }}"
      when: not is_empty

    - name: Add vrf
      set_fact:
        add_command: |-
          {{ logging_host_default }}{{ ' vrf Mgmt-vrf' if vrf_sup else '' }}
          {{ specify_log_host }}{{ ' vrf Mgmt-vrf' if vrf_sup else '' }}

    - name: test
      debug:
        msg: "{{ add_command.split('\n') }}"

#    - name: Add logging hosts
#      cisco.ios.ios_config:
#        lines: "{{ add_command.split('\n') }}"
#      when: add_command is defined and add_command | length > 0